---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crs
  namespace: external-secrets
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 10m
  path: ./infrastructure/dependencies/external-secrets/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-dependencies
